jodlgang/jodlgang/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url('^', include('jodlplatform.urls')),
]

jodlgang/jodlplatform/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from .forms import FaceAuthenticationForm

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^home/$', views.home, name='home'),
    url(r'^personal/$', views.personal_notes, name='personal'),
    url(r'^note/$', views.add_note, name='add_note'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'authentication_form': FaceAuthenticationForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
]

jodlgang/jodlplatform/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import UserManager


class User(AbstractBaseUser):
    id = models.AutoField('id', primary_key=True, blank=False)
    email = models.EmailField('email address', blank=False, unique=True, null=False)
    name = models.CharField('name', max_length=100, blank=True)
    is_staff = models.BooleanField('staff', default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_name(self):
        return self.name

    def __str__(self):
        return self.email

    def get_full_name(self):
        if len(self.name) > 0:
            return self.name
        return self.email

    def get_short_name(self):
        if len(self.name) > 0:
            return self.name
        return self.email

    # this method is required to login super user from admin panel
    def has_perm(self, perm, obj=None):
        return self.is_staff

    # this method is required to login super user from admin panel
    def has_module_perms(self, app_label):
        return self.is_staff


class Note(models.Model):
    text = models.CharField(max_length=512, blank=False)
    title = models.CharField(max_length=128, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=True)
    pub_date = models.DateTimeField(auto_now_add=True, blank=False)

jodlgang/jodlplatform/forms.py
from django.contrib.auth.forms import UsernameField
from django import forms
from django.contrib.auth import (
    authenticate, get_user_model,
)
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _


UserModel = get_user_model()


class FaceAuthenticationForm(forms.Form):
    username = UsernameField(
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True}),
    )

    face_img = forms.ImageField(label="Face image", required=True)

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the label for the "username" field.
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.data.get('password')

        # Reject if face image is missing
        if "face_img" not in self.request.FILES:
            raise forms.ValidationError(
                self.error_messages['invalid_login'],
                code='invalid_login',
                params={'face_img': "Face image is missing"}
            )

        # Reject if face image is not one of the allowed content types
        face_img = self.request.FILES["face_img"]
        if face_img.content_type not in {"image/jpeg", "image/png"}:
            raise forms.ValidationError(
                self.error_messages['invalid_login'],
                code='invalid_login',
                params={'face_img': "File format not recognized"}
            )

        # Reject large images
        if face_img.size > 1024 * 1024:
            raise forms.ValidationError(
                self.error_messages['invalid_login'],
                code='invalid_login',
                params={'face_img': "File too large"}
            )

        face_img = face_img.file

        if username is not None:
            self.user_cache = authenticate(self.request, username=username, password=password, face_img=face_img)
            if self.user_cache is None:
                # An authentication backend may reject inactive users. Check
                # if the user exists and is inactive, and raise the 'inactive'
                # error if so.
                try:
                    self.user_cache = UserModel._default_manager.get_by_natural_key(username)
                except UserModel.DoesNotExist:
                    pass
                else:
                    self.confirm_login_allowed(self.user_cache)
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache

jodlgang/jodlplatform/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Note


def index(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


@login_required(login_url="/login/")
def home(request):
    # Get the latest notes
    latest_notes = Note.objects.filter(public=True).order_by("-pub_date")[:30]

    context = {
        "notes": latest_notes
    }

    return render(request, "home.html", context=context)


@login_required(login_url="/login/")
def add_note(request):
    current_user = request.user
    if "note" in request.POST and "title" in request.POST:
        public = "public" in request.POST
        text = request.POST["note"]
        title = request.POST["title"]
        if len(text) > 0 and len(title):
            Note(author=current_user, text=text, title=title, public=public).save()
            return render(request, "added_note.html")

    # On error show the form again
    return render(request, "add_note.html")


@login_required(login_url="/login/")
def personal_notes(request):
    # Get all personal notes
    user_personal_notes = Note.objects.filter(author=request.user).order_by("-pub_date")

    context = {
        "notes": user_personal_notes
    }

    return render(request, "home.html", context=context)

jodlgang/templates/about.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <title>JODL GANG</title>
{% endblock %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">About</h1>
        <p class="lead">JODL GANG is an investment group whose fellow patrons provide consultation services to their trusting clients.</p>
    </div>

    <div class="container">
        <div class="card-deck mb-3">
            <p>This website provides a platform where registered patrons exchange brief notes and organize themselves. Patrons can also save private notes only to be seen by each individual himself.
                There are 530 active patrons, and registration is closed at the moment. There are several platforms available in different regions. Each of these platforms is maintained by one of our fellow patrons. The local ambassador of this site is <a href="mailto:{{ ambassador_email }}" title="Message {{ ambassador_email }}" class="ambassador-email">{{ ambassador_name }}</a>.</p>

            <p>Recently, the JODL GANG platfrom replaced the old password login for a much safer state-of-the-art face authentication system. To sign in, a patron must provide an image of his face alongside his email address. The face image must be a color image of size 224x224 pixels and must not be larger than 1MB.</p>
        </div>
    </div>
{% endblock %}

jodlgang/templates/add_note.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <title>Add note - JODL GANG</title>
{% endblock %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-5">Share your advice!</h1>

        <form method="post" style="max-width: 500px; padding: 15px; margin: auto;">
            {% csrf_token %}

            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" name="title" class="form-control" required/>
            </div>

            <div class="form-group">
                <textarea class="form-control" id="noteTextarea" name="note" rows="3" required></textarea>
            </div>

            <div class="form-group">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="public" value="on" id="isPublic" checked="checked">
                    <label class="form-check-label" for="isPublic">
                        Public
                    </label>
                </div>
            </div>

            <button class="btn btn-lg btn-primary btn-block" type="submit">Share</button>

            <a class="btn btn-outline-primary" href="/home/" style="width: 100%; margin-top: 30px;">Back</a>
        </form>
    </div>
{% endblock %}

jodlgang/templates/added_note.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <title>Added note - JODL GANG</title>
{% endblock %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-5">Thanks for sharing dude!</h1>

        <div style="max-width: 500px; padding: 15px; margin: auto;">
            <a class="btn btn-outline-primary" href="/home/" style="width: 100%; margin-top: 30px;">Back</a>
        </div>
    </div>
{% endblock %}

jodlgang/templates/base.html
{% extends "raw_base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <title>JODL GANG</title>
{% endblock %}

{% block body %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">JODL GANG</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="/about/">About</a>
        </nav>
        {% if request.user.is_authenticated %}
        <nav class="my-2 my-md-0 mr-md-3">
            <span class="p-2 text-dark">{{ user.get_username }}</span>
        </nav>
        <a class="btn btn-outline-primary logout" href="/logout/">Log out</a>
        {% else %}
        <a class="btn btn-outline-primary login" href="/login/">Sign in</a>
        {% endif %}
    </div>

    {% block content %}

    {% endblock %}

    <div class="container">
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                Contact our local ambassador&nbsp;<a href="mailto:{{ ambassador_email }}" title="Message {{ ambassador_email }}" class="ambassador-email">{{ ambassador_name }}</a>
            </div>
        </footer>
    </div>
{% endblock %}

jodlgang/templates/home.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <title>JODL GANG</title>
{% endblock %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-5">Overcome the fear of missing out and be a part of the movement!</h1>
        <p class="lead">The cyptocurrencies market is extremely volatile at the moment. Publish your advice and pump and
            dump with the other patrons.</p>
        <p>
            <a class="btn btn-primary btn-lg" href="/note/" role="button">Share your advice &raquo;</a>
            &nbsp;
            {% if request.get_full_path == "/home/" %}
                <a class="btn btn-primary btn-lg" href="/personal/" role="button">View your notes only &raquo;</a>
            {% else %}
                <a class="btn btn-primary btn-lg" href="/home/" role="button">View recent notes &raquo;</a>
            {% endif %}
        </p>
    </div>

    <div class="container">
        <!-- Latest notes go here -->
        <div class="list-group notes">
            {% for note in notes %}
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1 title">{{ note.title }}</h5>
                        <small class="date">{{ note.pub_date }}</small>
                    </div>
                    <p class="mb-1 text">{{ note.text }}</p>
                    <small class="author">{{ note.author.name }}</small>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

jodlgang/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <title>JODL GANG</title>
{% endblock %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">JODL GANG</h1>
        <p class="lead">Let us help you make a fortune on the cryptocurrency market. Since its foundation our fellow JODL GANG patrons have helped thousands of individuals like you to the success story of their life. Don't miss out and get in touch today!</p>
    </div>
{% endblock %}

jodlgang/templates/logged_out.html
{% extends "base.html" %}

{% block content %}
<p>Logged out!</p>

<a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

jodlgang/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    <title>Login</title>
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <!--
    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
    -->

    <form class="form-signin" method="post" action="{% url 'login' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center">
            <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        </div>

        <div class="text-center" id="errors">
            {% if form.errors %}
                <p>Permission denied</p>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.username.label_tag }}
            {% render_field form.username class="form-control" %}
        </div>

        <!--
        {{ form.password.label_tag }}
        {% render_field form.password class="form-control" %}
        -->

        <div class="form-group">
            <label for="id_face_img">A webcam photo of your face:</label>
            {% render_field form.face_img class="form-control" %}
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
{% endblock %}

jodlgang/templates/raw_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
      {% block title %}<title>FOMOGANG</title>{% endblock %}

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap Javascript -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </head>

  <body>
    {% block body %}{% endblock %}
  </body>

</html>